# Generated by Django 4.2.4 on 2023-09-03 19:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0004_vote"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together={("post", "voter")},
        ),
    ]
